### ISSUE TITLE
is this a virus

### ISSUE THREAD

**Issue by IshaanDixit07** [DmitrijVC/steam-blocker#1]
1. The File name is Odd
2. It has the logo of the drive which contains windows!

**Comment by FssAy** [comment]
Are you mentally retarded?
You have the source code, compile it on your own.

[VirusTotal](https://www.virustotal.com/gui/file/a2117576739d1a68057c86f672d383d0a60a29a132831f50e99720bfcaf864c1/details)
[Hybrid](https://hybrid-analysis.com/sample/ccf21784560279910ff36d4cd591b37506037f62e5705f6aeeb0de131abddc27)

**Comment by ghost** [comment]
Are you an idiot?
If you don't understand the code, don't claim it is a virus.
